// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamCooks.API.DbContext;

namespace SamCooks.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230817162749_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SamCooks.API.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("SamCooks.API.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAcceptedTerms")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAccountLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstTimeLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SamCooks.API.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSongs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7d58c75-18bc-4868-b54d-0a1fdf8fe94d"),
                            Bio = "21 Savage is a British rapper known for his <i>distinct trap style</i> and introspective lyrics. Born in London, he moved to Atlanta at a young age and emerged as a prominent figure in the hip-hop scene. His music often reflects on his personal experiences, addressing topics like <i>violence</i>, <i>poverty</i>, and <b><span style='color: red';>social injustice</span></b>.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(7087),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Atlanta, Georgia",
                            Name = "21 Savage",
                            Region = "South",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("d8b86cbe-fd86-4a8b-81f8-800b5e27e8c2"),
                            Bio = "3rd Bass was an American hip-hop group known for their witty and <span class='pir'>socially conscious</span> lyrics. Consisting of MC Serch, Prime Minister Pete Nice, and DJ Richie Rich, they rose to prominence in the late 1980s and early 1990s. Their music often tackled themes of racial inequality, politics, and cultural criticism.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8212),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "",
                            Name = "3rd Bass",
                            Region = "North",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("e3511cd1-8c6c-44fb-908d-1107a4e8e8d9"),
                            Bio = "50 Cent is an American rapper and actor who gained popularity with his debut album 'Get Rich or Die Tryin'.' Born Curtis Jackson, he rose to prominence in the early 2000s with his gritty lyrics and captivating storytelling. Beyond his music career, 50 Cent has ventured into entrepreneurship and acting, showcasing his versatility and business acumen.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8265),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Queens, New York",
                            Name = "50 Cent",
                            Region = "North",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("e4aba257-4e44-4fec-9f36-dabbac9e6078"),
                            Bio = "Akinyele is a provocative and controversial Hip Hop artist known for pushing boundaries with his explicit lyrics. His debut album 'Vagina Diner' gained attention for its daring content. Akinyele's music often sparks discussions about societal taboos and challenges traditional norms.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8269),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Queens, New York",
                            Name = "Akinyele",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("b0577578-89ca-4d61-afab-aac673fa4bfb"),
                            Bio = "Beastie Boys were an American rap/rock group known for their energetic performances and genre-blending music. Consisting of Michael Diamond (Mike D), Adam Horovitz (Ad-Rock), and Adam Yauch (MCA), they emerged in the 1980s as pioneers of hip-hop and alternative music fusion. Their influential career spanned decades, leaving an indelible impact on the music industry.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8272),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brooklyn, New York",
                            Name = "Beastie Boys",
                            Region = "North",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("12b86ab3-08b1-4597-afeb-c259809fadfe"),
                            Bio = "Big Daddy Kane is an American rapper and actor known for his smooth delivery and influential contributions to hip-hop. With his charismatic stage presence and intricate wordplay, he became one of the leading figures in the golden age of hip-hop in the late 1980s and early 1990s. His lyrical prowess and suave style influenced generations of artists.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8278),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brooklyn, New York",
                            Name = "Big Daddy Kane",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("c21a0b21-e882-4fc0-a723-ab568dee850e"),
                            Bio = "Big Pun, whose real name was Christopher Rios, was a highly influential Puerto Rican-American rapper known for his exceptional lyricism and impactful storytelling. He left a lasting legacy on the hip-hop community as one of the first Latino rappers to achieve mainstream success. Despite his untimely passing, his contributions to the genre continue to inspire and influence artists to this day.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8346),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Bronx, New York",
                            Name = "Big Pun",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("e72f8147-068a-4dfc-8076-7ddfd0d0ff4d"),
                            Bio = "Biz Markie was an American rapper, beatboxer, and producer known for his humorous and lighthearted style. With his distinctive baritone voice and playful lyrics, he achieved mainstream success in the late 1980s. Biz Markie's contributions to hip-hop extended beyond his music, as he also served as a DJ and appeared in films and TV shows. Additionally, he subtly made <span class='pir';>political statements</span> in his music, demonstrating a slight bit of activism.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8348),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "New York, New York",
                            Name = "Biz Markie",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("0d869f3a-726a-4801-8959-262f0b9a909f"),
                            Bio = "Black Eyed Peas is an American musical group known for their eclectic blend of hip-hop, pop, and electronic music. Consisting of will.i.am (William James Adams Jr.), apl.de.ap (Allan Pineda Lindo), Taboo (Jaime Luis Gomez), and Fergie (Stacy Ann Ferguson), The group's music often carries socially conscious messages and promotes positivity and unity.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8350),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Los Angeles, California",
                            Name = "Black Eyed Peas",
                            Region = "West",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("d8643739-f72e-42f0-93f6-48ee78958529"),
                            Bio = "Black Moon is an American hip hop group from Brooklyn, New York, formed in the early 1990s. The group consists of members Buckshot, 5 ft, and DJ Evil Dee. Known for their underground sound and <span class='pir'>contribution to the creation of hardcore hip-hop with a focus on social consciousness</span>, they are acclaimed for albums like 'Enta da Stage'.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8354),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brooklyn, New York",
                            Name = "Black Moon",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("2d9ceb0d-ef78-45bf-ad55-cc7f9901ae0f"),
                            Bio = "Bone Thugs-N-Harmony is an American hip-hop group known for their melodic harmonies and rapid-fire delivery. Formed in Cleveland, Ohio, they rose to prominence in the 1990s with hits like 'Tha Crossroads' and '1st of tha Month'. Their unique style and introspective lyrics made them influential figures in the rap scene.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8356),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Cleveland, Ohio",
                            Name = "Bone Thugs-N-Harmony",
                            Region = "North",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("9c42203f-12eb-4725-9bdf-ba5df28cbeb1"),
                            Bio = "Busta Rhymes is an American rapper, singer, and actor known for his energetic performances and rapid-fire rhymes. With a career spanning several decades, he has released numerous chart-topping hits and collaborated with various artists. Busta Rhymes is celebrated for his dynamic flow and charismatic stage presence.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8358),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brooklyn, New York",
                            Name = "Busta Rhymes",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("cd8c0d16-8147-48a3-b79f-c41f3f3388e0"),
                            Bio = "Canibus is an American rapper known for his intricate wordplay and lyrical depth. Emerging in the late 1990s, he gained attention for his technical skills and thought-provoking verses. Canibus's music often explores complex themes and showcases his intellectual approach to hip-hop.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8360),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Jamaica, Queens, New York",
                            Name = "Canibus",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("ad7dd979-1452-40f7-abfa-48f0fb090714"),
                            Bio = "Cardi B is an American rapper, songwriter, and actress who rose to fame with her chart-topping debut single 'Bodak Yellow'. Known for her charismatic personality and unapologetic lyrics, she has become one of the most successful female artists in the music industry. Cardi B's bold and confident style has made her a cultural icon.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8362),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "New York, New York",
                            Name = "Cardi B",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("9d4312fa-04a0-46c4-ace1-3cd5db85199a"),
                            Bio = "Chancelor Bennett, better known by his stage name Chance the Rapper, is an American rapper, singer, songwriter, and record producer. He is known for his eclectic mix of hip hop, gospel, and soul music, as well as his <span class='pir';>socially conscious</span> lyrics.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8417),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Chicago, Illinois",
                            Name = "Chance the Rapper",
                            Region = "North",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("b6117d40-fad4-4101-8f91-861988862778"),
                            Bio = "Childish Gambino, also known as Donald Glover, is a multi-talented artist who excels in music, acting, writing, and producing. With critically acclaimed albums like 'Awaken, My Love!' and the hit single 'This Is America', he has proven himself as an innovative and socially conscious artist. Childish Gambino's work often explores themes of race, identity, and cultural commentary.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8420),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Stone Mountain, Georgia",
                            Name = "Childish Gambino",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("c1ea5e3f-2080-406f-b300-58e919430f6f"),
                            Bio = "Common is an American rapper, actor, and activist known for his introspective and socially conscious lyrics. With a career spanning over three decades, he has released acclaimed albums and collaborated with various artists. Common's music often delves into themes of love, self-reflection, and social issues.",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8423),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Chicago, Illinois",
                            Name = "Common",
                            Region = "North",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("4aa0a587-22ad-4d74-a4b2-4af7a155b9e1"),
                            Bio = "Cypress Hill is an American hip-hop group...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8426),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "South Gate, California",
                            Name = "Cypress Hill",
                            Region = "West",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("21396070-8cb6-4013-88b7-9bc770fbdea3"),
                            Bio = "De La Soul is an American hip-hop trio...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8428),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Amityville, New York",
                            Name = "De La Soul",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("e77e56bb-1965-4bcc-bf97-59fe949ef32e"),
                            Bio = "Digital Underground was an American hip-hop group...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8430),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Oakland, California",
                            Name = "Digital Underground",
                            Region = "West",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("2a1ec110-02f9-439e-8c98-62118414460e"),
                            Bio = "DJ Jazzy Jeff & The Fresh Prince, consisting of DJ Jazzy Jeff...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8432),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Philadelphia, Pennsylvania",
                            Name = "DJ Jazzy Jeff & The Fresh Prince",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("8ec42dd7-70aa-41c7-904c-8a35c9498ac5"),
                            Bio = "Denzel Curry is an American rapper and songwriter...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8434),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Carol City, Florida",
                            Name = "Denzel Curry",
                            Region = "South",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("216ee8ad-45f2-4821-ae2a-a31513b582b2"),
                            Bio = "DMX, also known as Dark Man X, was a prominent American rapper and actor...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8439),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Yonkers, New York",
                            Name = "DMX",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("ba8f37ad-2c5e-47f4-a698-185d132465bf"),
                            Bio = "Don Trip (Christopher Donnie Wallace Jr) is a Memphis-based Hip Hop artist...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8441),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Memphis, Tennessee",
                            Name = "Don Trip",
                            Region = "South",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("a86aa0bb-2f52-4c77-ae95-8e13e8647f46"),
                            Bio = "Doug E. Fresh is an American rapper, beatboxer, and producer...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8443),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Barbados, New York",
                            Name = "Doug E. Fresh",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("43e15e26-29c5-43c6-a234-cdb05102d452"),
                            Bio = "DJ Quik is an American rapper, record producer, and DJ...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8445),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Compton, California",
                            Name = "DJ Quik",
                            Region = "West",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("82d20e7d-c16d-4871-aa41-e63dd85fc7d9"),
                            Bio = "Drake is a Canadian rapper, singer, songwriter, and actor...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8447),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Ontario, Canada",
                            Name = "Drake",
                            Region = "North",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("810fd050-69f1-4df7-bd8e-538fdd99cd7a"),
                            Bio = "El-P, whose real name is Jaime Meline, is an American rapper...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8449),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brooklyn, New York",
                            Name = "El-P",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("7e8c0d97-d711-4b11-860d-fe8ebed81e88"),
                            Bio = "Eminem, also known as Marshall Mathers or Slim Shady, is an American rapper...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8451),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Detroit, Michigan",
                            Name = "Eminem",
                            Region = "North",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("0d113502-3201-400b-9032-80b3d08c98e0"),
                            Bio = "EPMD, which stands for Erick and Parrish Making Dollars, is an American hip-hop duo...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8453),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brentwood New York",
                            Name = "EPMD",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("06668236-a70e-4f92-b9ed-d84c8a92461a"),
                            Bio = "Eric B & Rakim were an American hip-hop duo known for their groundbreaking contributions...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8457),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Long Island, New York",
                            Name = "Eric B & Rakim",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("d89be7b5-908f-4b71-af1e-6413f287b960"),
                            Bio = "Fabolous, born John David Jackson, is an American rapper and songwriter from Brooklyn...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8459),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brooklyn, New York",
                            Name = "Fabolous",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("08e717ee-1bb9-4d78-a960-806e638edabd"),
                            Bio = "Fat Boys were an American hip-hop trio known for their lighthearted and comedic approach...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8461),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brooklyn, New York",
                            Name = "Fat Boys",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("f70ade42-0591-4eaf-8fff-4562a48a914e"),
                            Bio = "Fearless Four was an American hip-hop group known for their energetic performances...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8465),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "New York, New York",
                            Name = "Fearless Four",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("829ff282-771f-4163-b623-c6a376dbccf2"),
                            Bio = "Fugees, comprised of Wyclef Jean, Lauryn Hill, and Pras Michel, were an American hip-hop...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8467),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "South Orange, New Jersey",
                            Name = "Fugees",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("76d60b6b-f561-4f11-a81b-e56714ee4a26"),
                            Bio = "Nayvadius DeMun Wilburn, better known by his stage name Future, is an American rapper...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8469),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Atlanta, Georgia",
                            Name = "Future",
                            Region = "South",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("7c52c5fd-a42e-489f-8936-6cfd12e396dc"),
                            Bio = "Gang Starr was an American hip-hop duo consisting of Guru and DJ Premier. Known for...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8471),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Brooklyn, New York",
                            Name = "Gang Starr",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("4eea05c7-76a9-463e-b4b3-ecf36c9da2c7"),
                            Bio = "Grandmaster Flash and the Furious Five were an American hip-hop group known for...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8473),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "South Bronx, New York",
                            Name = "Grand Master Flash and the Furious 5",
                            Region = "East",
                            TotalSongs = 0
                        },
                        new
                        {
                            Id = new Guid("de4fa6c0-69b4-440d-8bfb-1a03d4e50aa9"),
                            Bio = "Gunna, also known as Sergio Giavanni Kitchens, is an American rapper and songwriter...",
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 22, DateTimeKind.Utc).AddTicks(8478),
                            IsActive = false,
                            IsDeleted = false,
                            Location = "Atlanta, Georgia",
                            Name = "Gunna",
                            Region = "South",
                            TotalSongs = 0
                        });
                });

            modelBuilder.Entity("SamCooks.API.Entities.ArtistEra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("EraId");

                    b.ToTable("ArtistEra");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5766d40c-03dc-4cbc-9311-68e02fd2c714"),
                            ArtistId = new Guid("e7d58c75-18bc-4868-b54d-0a1fdf8fe94d"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 19, DateTimeKind.Utc).AddTicks(7876),
                            EraId = new Guid("2fd8696a-414b-41e7-a661-b0dbddc309fa"),
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("24cddc59-1ed9-4e36-b90a-874f344a9cd7"),
                            ArtistId = new Guid("e7d58c75-18bc-4868-b54d-0a1fdf8fe94d"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 19, DateTimeKind.Utc).AddTicks(9323),
                            EraId = new Guid("24889416-93f3-44ee-a240-d3d03c5acdd2"),
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("43d495e0-a269-46ef-aff4-2f8bd1ab3435"),
                            ArtistId = new Guid("d8b86cbe-fd86-4a8b-81f8-800b5e27e8c2"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 19, DateTimeKind.Utc).AddTicks(9364),
                            EraId = new Guid("d8b86cbe-fd86-4a8b-81f8-800b5e27e8c2"),
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("d8b86cbe-fd86-4a8b-81f8-800b5e27e8c2"),
                            ArtistId = new Guid("e3511cd1-8c6c-44fb-908d-1107a4e8e8d9"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 19, DateTimeKind.Utc).AddTicks(9370),
                            EraId = new Guid("e3511cd1-8c6c-44fb-908d-1107a4e8e8d9"),
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("e3511cd1-8c6c-44fb-908d-1107a4e8e8d9"),
                            ArtistId = new Guid("e4aba257-4e44-4fec-9f36-dabbac9e6078"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 19, DateTimeKind.Utc).AddTicks(9375),
                            EraId = new Guid("68005290-a3c7-4973-bd05-4ee4c3395d4d"),
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("e4aba257-4e44-4fec-9f36-dabbac9e6078"),
                            ArtistId = new Guid("b0577578-89ca-4d61-afab-aac673fa4bfb"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 19, DateTimeKind.Utc).AddTicks(9382),
                            EraId = new Guid("d8b86cbe-fd86-4a8b-81f8-800b5e27e8c2"),
                            IsActive = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SamCooks.API.Entities.Era", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Era");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fd8696a-414b-41e7-a661-b0dbddc309fa"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(3094),
                            Date = "1995",
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("68005290-a3c7-4973-bd05-4ee4c3395d4d"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(3495),
                            Date = "1990",
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("24889416-93f3-44ee-a240-d3d03c5acdd2"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(3514),
                            Date = "1999",
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("d8b86cbe-fd86-4a8b-81f8-800b5e27e8c2"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(3518),
                            Date = "1980",
                            IsActive = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("e3511cd1-8c6c-44fb-908d-1107a4e8e8d9"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(3520),
                            Date = "2000",
                            IsActive = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SamCooks.API.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Keyword");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1326157-0193-4fff-aa13-6c024b6db075"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(8301),
                            IsActive = false,
                            IsDeleted = false,
                            Word = "#Violence"
                        },
                        new
                        {
                            Id = new Guid("3a2d81f8-e711-4b65-bb25-e858c9718337"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(8680),
                            IsActive = false,
                            IsDeleted = false,
                            Word = "#Success"
                        },
                        new
                        {
                            Id = new Guid("038075d4-0f58-40f3-b94c-8e62bfafdcac"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(8698),
                            IsActive = false,
                            IsDeleted = false,
                            Word = "#Loyalty"
                        },
                        new
                        {
                            Id = new Guid("87631796-cb7e-4f12-9672-40de4f95666c"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(8702),
                            IsActive = false,
                            IsDeleted = false,
                            Word = "#LifeOverWealthOrDeath"
                        },
                        new
                        {
                            Id = new Guid("a814b9c4-1f18-42e7-8305-233ba7fa7e4c"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(8705),
                            IsActive = false,
                            IsDeleted = false,
                            Word = "#Struggles"
                        },
                        new
                        {
                            Id = new Guid("b69ba75f-7a49-4f3e-b0f0-7a3d9fb550c9"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(8710),
                            IsActive = false,
                            IsDeleted = false,
                            Word = "#Betrayal"
                        },
                        new
                        {
                            Id = new Guid("31f002c8-0686-4283-9cd0-b56ba095930a"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 23, DateTimeKind.Utc).AddTicks(8713),
                            IsActive = false,
                            IsDeleted = false,
                            Word = "#GunViolence"
                        });
                });

            modelBuilder.Entity("SamCooks.API.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CulturallySignificant")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedLyrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallTheme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonOfSelection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SociallyConscious")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24cddc59-1ed9-4e36-b90a-874f344a9cd7"),
                            ArtistId = new Guid("e7d58c75-18bc-4868-b54d-0a1fdf8fe94d"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 24, DateTimeKind.Utc).AddTicks(6528),
                            CulturallySignificant = 1,
                            IsActive = false,
                            IsDeleted = false,
                            LinkedLyrics = "https://genius.com/21-savage-a-lot-lyrics",
                            Name = "A Lot",
                            OverallTheme = "Reflection",
                            ReasonOfSelection = "This song addresses various social issues and personal experiences, including the effects of violence, racism, and the struggle for success.",
                            SociallyConscious = 1
                        });
                });

            modelBuilder.Entity("SamCooks.API.Entities.SongKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("SongId");

                    b.ToTable("SongKeyword");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1326157-0193-4fff-aa13-6c024b6db075"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 24, DateTimeKind.Utc).AddTicks(2539),
                            IsActive = false,
                            IsDeleted = false,
                            KeywordId = new Guid("c1326157-0193-4fff-aa13-6c024b6db075"),
                            SongId = new Guid("24cddc59-1ed9-4e36-b90a-874f344a9cd7")
                        },
                        new
                        {
                            Id = new Guid("cdec1b46-f382-4b34-a376-c4e1952f6340"),
                            CreatedOn = new DateTime(2023, 8, 17, 16, 27, 49, 24, DateTimeKind.Utc).AddTicks(3317),
                            IsActive = false,
                            IsDeleted = false,
                            KeywordId = new Guid("3a2d81f8-e711-4b65-bb25-e858c9718337"),
                            SongId = new Guid("24cddc59-1ed9-4e36-b90a-874f344a9cd7")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SamCooks.API.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SamCooks.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SamCooks.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SamCooks.API.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SamCooks.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SamCooks.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SamCooks.API.Entities.ArtistEra", b =>
                {
                    b.HasOne("SamCooks.API.Entities.Artist", "Artist")
                        .WithMany("Eras")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SamCooks.API.Entities.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SamCooks.API.Entities.Song", b =>
                {
                    b.HasOne("SamCooks.API.Entities.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SamCooks.API.Entities.SongKeyword", b =>
                {
                    b.HasOne("SamCooks.API.Entities.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SamCooks.API.Entities.Song", "Song")
                        .WithMany("Keywords")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
